# Site settings
title: Michelle Torres
email: smtorres@ucla.edu
description: Assistant Professor of Political Science, University of California, Los Angeles
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://smtorres.org" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
#500px_url:
#facebook_url:
github_url: https://github.com/smtorres
#gitlab_url: https://gitlab.com/u/andrewbanchich
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
#instagram_url:
#linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
#pinterest_url:
email_url: smtorres@ucla.edu
twitter_url: https://twitter.com/michtorresp


# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
